In [13]:
import numpy as np
import sys

In [51]:
var1 = np.array([1,2,4])
var2 = np.array([4,5,3])
var3 = np.array([[1,2,4,5,6,343,23,32],[4,3,53,23,242,2646,756,956]])

print(type(var1))

var1 * var2 

<class 'numpy.ndarray'>


array([ 4, 10, 12])

In [42]:
#Get Dimension e.g 1D, 2D, 3D
print(var1.ndim,"---",var3.ndim)

#Get Shape
print(var1.shape,"---",var3.shape)

# Get Type (data type)
var1.dtype

1 --- 2
(3,) --- (2, 8)


dtype('int64')

In [52]:
#Get Size in bytes
print(var1.itemsize)

#Get Total Size in bytes
print(var1.nbytes)

8
24


In [50]:
# Get Specific item [r,c]
print(var3)
print(var3[1,6])

#Get specific row
print(var3[0,:])

#Get specific column
print(var3[:,2])

# Startindex:Endindex:Stepsize
print(var3[0,0:7:2])

[[   1    2    4    5    6  343   23   32]
 [   4    3   53   23  242 2646  756  956]]
756
[  1   2   4   5   6 343  23  32]
[ 4 53]
[ 1  4  6 23]


## 3D Example

In [65]:
var3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(var3d)

#Get Specific element
print(var3d[0,0,0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
1
