In [3]:
import numpy as np

In [4]:
# create a numpy array using arange function. Similar to python range() method
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Divide a range in equal intervals.

In [7]:
# It divides the range from 0 to 5 in 10 equal interval. Good while plotting graph
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

## Identity Matrix
The sqare matix where diagonale elements are 1. Rest all elements are 0

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array with Random number
#### Check the difference between rand and randn

In [9]:
# Generate 3 by 2 matrix with random elements of value between 0 to 1
np.random.rand(3,2)

array([[0.30613975, 0.90359999],
       [0.60618944, 0.89634322],
       [0.81300803, 0.94535023]])

In [10]:
np.random.randn(3,2)

array([[-0.49259815, -0.48444134],
       [-0.59162097, -0.95730311],
       [ 0.69772678,  0.15751659]])

In [11]:
# generate 10 random number lower limit 1 (inclusive) and upper limit 100 (exclusive)
np.random.randint(1,100,10)

array([17, 21, 29, 85, 26, 59, 21, 48, 77, 79])

In [12]:
ar = np.random.randint(1,100,25)
ar

array([32, 28, 36, 70, 73,  1, 57, 33,  7, 74, 92, 58, 52,  5, 36, 83, 93,
       95, 26, 50, 59, 77,  5, 50, 35])

In [13]:
# write the above generated random number in the 5 by 5 matrix
ar2 = ar.reshape(5,5)
ar2

array([[32, 28, 36, 70, 73],
       [ 1, 57, 33,  7, 74],
       [92, 58, 52,  5, 36],
       [83, 93, 95, 26, 50],
       [59, 77,  5, 50, 35]])

In [14]:
# max value of array
ar.max()

95

In [15]:
ar.min()

1

In [16]:
# index of max value
ar.argmax()

17

In [17]:
# Find the order of the array
ar2.shape

(5, 5)

In [18]:
# find the data type of the array
ar2.dtype

dtype('int64')

## Access 2D array using two and single bracket

In [19]:
arr_2d = np.array([[5,10,4],[54,32,51],[65,44,78]])
arr_2d[1][2]

51

In [20]:
arr_2d[1,2]

51

In [21]:
arr_2d

array([[ 5, 10,  4],
       [54, 32, 51],
       [65, 44, 78]])

In [23]:
# use slice to display top right corner elements
arr_2d[:2,1:]

array([[10,  4],
       [32, 51]])

In [24]:
arr_2d[1:]

array([[54, 32, 51],
       [65, 44, 78]])

## Conditional indexing

In [25]:
ar

array([32, 28, 36, 70, 73,  1, 57, 33,  7, 74, 92, 58, 52,  5, 36, 83, 93,
       95, 26, 50, 59, 77,  5, 50, 35])

In [37]:
ar>20

array([ True,  True,  True,  True,  True, False,  True,  True, False,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True])

In [31]:
bool_arr = ar > 40
bool_arr

array([False, False, False,  True,  True, False,  True, False, False,
        True,  True,  True,  True, False, False,  True,  True,  True,
       False,  True,  True,  True, False,  True, False])

In [32]:
ar[bool_arr]

array([70, 73, 57, 74, 92, 58, 52, 83, 93, 95, 50, 59, 77, 50])

In [33]:
ar

array([32, 28, 36, 70, 73,  1, 57, 33,  7, 74, 92, 58, 52,  5, 36, 83, 93,
       95, 26, 50, 59, 77,  5, 50, 35])

In [36]:
# same the above step can be done using one line. Display elements which is more than 40
ar[ar>40]

array([70, 73, 57, 74, 92, 58, 52, 83, 93, 95, 50, 59, 77, 50])

## Addition of two matrices

In [49]:
A = np.random.randint(1,10,9)
A = A.reshape(3,3)
A


array([[5, 8, 6],
       [8, 3, 6],
       [6, 7, 1]])

In [50]:
B = np.random.randint(1,10,9)
B = B.reshape(3,3)
B

array([[1, 8, 1],
       [6, 9, 2],
       [6, 9, 3]])

In [51]:
A + B

array([[ 6, 16,  7],
       [14, 12,  8],
       [12, 16,  4]])

## Multiplication of Two matrices

In [52]:
A * B

array([[ 5, 64,  6],
       [48, 27, 12],
       [36, 63,  3]])

In [53]:
np.multiply(A,B)

array([[ 5, 64,  6],
       [48, 27, 12],
       [36, 63,  3]])

In [54]:
np.matmul(A,B)

array([[ 89, 166,  39],
       [ 62, 145,  32],
       [ 54, 120,  23]])